In [287]:
import numpy as np
import pandas as pd

class CustomLinearRegresson:
    def __init__(self):
        self.m = None
        self.b = None
    
    def fit(self, X_train, y_train):
        
        X = X_train.flatten()
        y = y_train.flatten()
        
        num = 0
        deno = 0
        for i in range(X.shape[0]):
            num +=((X[i] - X.mean())*(y[i] - y.mean()))
            deno +=((X[i] - X.mean())**2)
        self.m = num/deno
        self.b = y.mean() - (self.m * X.mean())
        print(self.m)
        print(self.b)
        
    def predict(self,X_test):
        return self.m * X_test + self.b

In [288]:
df = pd.read_csv('C:/Users/patil/Downloads/Salary_dataset.csv')
df.head()

Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [289]:
df  = df.drop(columns=['Unnamed: 0'])
df['Salary'] = df['Salary'].astype(int)

In [290]:
X = df.iloc[:,0].values
y = df.iloc[:,1].values

In [291]:
X

array([ 1.2,  1.4,  1.6,  2.1,  2.3,  3. ,  3.1,  3.3,  3.3,  3.8,  4. ,
        4.1,  4.1,  4.2,  4.6,  5. ,  5.2,  5.4,  6. ,  6.1,  6.9,  7.2,
        8. ,  8.3,  8.8,  9.1,  9.6,  9.7, 10.4, 10.6])

In [292]:
y

array([ 39344,  46206,  37732,  43526,  39892,  56643,  60151,  54446,
        64446,  57190,  63219,  55795,  56958,  57082,  61112,  67939,
        66030,  83089,  81364,  93941,  91739,  98274, 101303, 113813,
       109432, 105583, 116970, 112636, 122392, 121873])

In [293]:
df.head()

YearsExperience  Salary
0              1.2   39344
1              1.4   46206
2              1.6   37732
3              2.1   43526
4              2.3   39892

In [294]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)


In [295]:
print(X_train.shape[0])

24


In [296]:
lr = CustomLinearRegresson()

In [297]:
lr.fit(X,y)

9449.962321455077
24848.203966523193


In [298]:
X_test.astype(int)

array([5, 7, 4, 6, 4, 6])

In [299]:
y_test

array([83089, 98274, 63219, 93941, 61112, 91739])

In [300]:
print("Dataset assumption:", y_test[0])
print("Our model's prediction:", lr.predict(X_test[0]).astype(int))

Dataset assumption: 83089
Our model's prediction: 75878
